### ISSUE TITLE
Save money for salvadors08151982

### ISSUE THREAD

**Issue by Moroe365** [MillaBasset/cambridge-modpack#12]
Disposal of if It isn't a need disposal of illegalities
I don't have to care for anybody
It isn't a need to have to 
I have to be clean and sober or I will have to get clean and sober 
I can get a job and begin to support myself 
I can sign up for benefits 
I can sign into a homeless shelter if adjustment needs to be made for a home 
I can save money to rent a home 
I can save money to pay my rent for my house 
I can save money to pay for my utilities 
I can save money to wash my clothes 
I can save my money to buy softdrinks
I can save my cigarettes 
I am Uncircumcised 
I believe I serve a deserving God
I love God
The spirit of the Greek God Padon
An Hebrew God Jehovah
I accept Jesus Christ of Nazareth into my heart
I love God
I obey God
I teach to lead a home in the Ways of the Lord
I am a Soldier of God
I work for the righteousness of God
All things are of Grace and Mercy of God
Repent and come to the repentance of the remission of your sins
Forgive your neighbor and give your neighbor Grace and they don't exist
Praise the name of the Lord I Am
Trust in the faith of God 
Don't sin
Don't take advantage of anybody 
Don't expect anything from anybody 
Don't lie
Don't steal
I don't donate
I don't control anybody but I care
They can and I can't 
It isn't welcomed 
They aren't welcomed 
They aren't welcomed for things I paid for or things I paid for you with permission 
I am an omnivore
I have needs and my needs have the rights to be mete
I need: money, shelter, clothes, a car and a truck.
I need clean health water and food from the seven basic food groups
I need care, rest, sleep, breathe, and awaken
Don't flush soap nor trash down the toilet 
When turn off the power first when working on electricity
> Ask for permission and understand to accept the answer of - # - [ ] no__~~```
@Moroe365 
```~~__

**Comment by infinifen** [comment]
??
what does this have to do with the modpack exactly

**Comment by Moroe365** [comment]
> Disposal of if It isn't a need disposal of illegalities
> I don't have to care for anybody
> It isn't a need to have to 

I am a honest and kind person

**Comment by Tetro48** [comment]
why did you create an account just to make this issue?

**Comment by Tetro48** [comment]
This issue shall be closed. Issue #12 is not related to the modpack.

**Comment by nothing1649** [comment]
stfu scammer bot
