### ISSUE TITLE
Score Drain

### ISSUE THREAD

**Issue by MillaBasset** [MillaBasset/cambridge-modpack#17]
Due to some tensions and old drama between myself and the creator of the mode, I will be removing it from the modpack. This issue serves mostly as a note to myself as I can only remove it after the ongoing tourney in the Cambridge Discord.

**Comment by MillaBasset** [comment]
In reference to #18: No version of the mode will exist in this repository going forward.

**Comment by MarkGamed7794** [comment]
Oh come on, I was proud of that mode!
